### ISSUE TITLE
Double info on user profile on Elgg 3.3.14

### ISSUE THREAD

**Issue by laurentiustan86** [iionly/lastlogin#1]
I installed this plugin and what ever I do, I get double details on user profiles like shown bellow:
![Profile-Impulsuri-ro](https://user-images.githubusercontent.com/16665799/102881023-ea133100-4454-11eb-8b6e-d85ce92fdf3e.png)

**Comment by iionly** [comment]
I can't reproduce.

Are you using the latest version of the Lastlogin plugin (i.e. version 3.3.0 on Elgg 3.3)? Had you installed an older version before that you upgraded from? If you upgraded from an older version, have you followed the instructions in the README to replace the Lastlogin plugin folder completely to make sure no outdated files remain?

If all this does not help, have to tested if some other 3rd party plugin is causing the problem if used together with the Lastlogin plugin?

**Comment by laurentiustan86** [comment]
My bad, I did just rewrite the plugin folder. Just did a full replace and now works, sorry!

**Comment by iionly** [comment]
Glad you got it sorted out and thanks for reporting that you got it working.
